MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (21, 42, 84, 168, 332)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 21
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    POSTPROCESS_MASKS_THRESHOLD: 0.5
  MASK_ON: True
DATASETS:
  TRAIN: ("voc_2012_train_aug_cocostyle_BBAM_fg_85_ignore_2_mcg",)
  TEST: ("voc_2012_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN: (416, 440, 464, 488, 512)
  MAX_SIZE_TEST: 800
  MIN_SIZE_TEST: 512
SOLVER:
  BASE_LR: 0.008
  WEIGHT_DECAY: 0.0001
  STEPS: (16000,)
  MAX_ITER: 20005
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 4000
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "BBAM_Mask_RCNN_logs_mcg85_v2"